version: '2'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codered_local
    volumes:
      - ./db/postgres:/db/postgres
